CREATE DATABASE PROYECTOGIMNASIO

CREATE TABLE USUARIOS
(
CODIGO INT,
CORREO VARCHAR(50),
CLAVE VARCHAR (50) NOT NULL,
NOMBRE VARCHAR (50) NOT NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO),
CONSTRAINT UQ_UNIQUE UNIQUE(CORREO)
)

CREATE TABLE CLIENTES
(
CODIGO INT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR (50) NULL,
TELEFONO VARCHAR (15) NULL,
USUARIO INT,
CONSTRAINT PK_CODIGOCLIENTE PRIMARY KEY (CODIGO),
CONSTRAINT PK_USUARIO1 FOREIGN KEY (USUARIO) REFERENCES  USUARIOS (CODIGO)
)

CREATE TABLE PRODUCTO 
(
CODIGO INT,
NOMBRE VARCHAR(50) NOT NULL,
PRECIO MONEY DEFAULT 0,
CONSTRAINT PK_CODIGOPRODUCTO PRIMARY KEY (CODIGO)
)

CREATE TABLE PROVINCIA
(
CODIGO INT,
NOMBRE VARCHAR(50) NOT NULL,
CONSTRAINT PK_CODIGOPROVINCIA PRIMARY KEY (CODIGO)
)

CREATE TABLE CANTON
(
CODIGO INT,
NOMBRE VARCHAR(50) NOT NULL,
CODIGO_PROVINCIA INT,
CONSTRAINT PK_CODIGOCANTON PRIMARY KEY (CODIGO),
CONSTRAINT FK_CODIGOPROVINCIA FOREIGN KEY (CODIGO_PROVINCIA) REFERENCES PROVINCIA(CODIGO)
)

CREATE TABLE DISTRITO
(
CODIGO INT,
NOMBRE VARCHAR(50) NOT NULL,
CODIGO_CANTON INT,
CONSTRAINT PK_CODIGODISTRITO PRIMARY KEY (CODIGO),
CONSTRAINT FK_CODIGOCANTON FOREIGN KEY (CODIGO_CANTON) REFERENCES CANTON(CODIGO)
)

CREATE TABLE DIRECCIONES
(
CODIGO INT IDENTITY,
CODIGO_CLIENTE INT,
CODIGO_PROVINCIA INT,
CODIGO_CANTON INT,
CODIGO_DISTRITO INT,
CONSTRAINT PK_CODIGODIRECCIONES PRIMARY KEY (CODIGO),
CONSTRAINT FK_CODIGOCLIENTES FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO),
CONSTRAINT FK_CODIGOPROVINCIA1 FOREIGN KEY (CODIGO_PROVINCIA) REFERENCES PROVINCIA(CODIGO),
CONSTRAINT FK_CODIGOCANTON1 FOREIGN KEY (CODIGO_CANTON) REFERENCES CANTON(CODIGO),
CONSTRAINT FK_CODIGODISTRITO FOREIGN KEY (CODIGO_DISTRITO) REFERENCES DISTRITO(CODIGO)
)

CREATE TABLE MAE_FACTURA
(
NFACTURA INT IDENTITY,
FECHA DATETIME,
CODIGO_CLIENTE INT,
TOTAL MONEY,
CONSTRAINT PK_NFACTURA PRIMARY KEY (NFACTURA),
CONSTRAINT FK_CODIGOCLIENTE2 FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO)
)

CREATE TABLE DET_FACTURA
(
CODIGO INT IDENTITY,
NFACTURA INT,
CODIGO_PRODUCTO INT,
CANTIDAD INT,
PRECIO MONEY,
CONSTRAINT PK_CODIGODETFACTURA PRIMARY KEY (CODIGO),
CONSTRAINT FK_NFACTURA FOREIGN KEY (NFACTURA) REFERENCES MAE_FACTURA(NFACTURA),
CONSTRAINT FK_CODIGOPRODUCTO1 FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO (CODIGO)
)
